name: Build and Deploy Documentation

on:
  push:
    branches: [main]
    paths: ["docs/**"]
  pull_request:
    branches: [main]
    paths: ["docs/**"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build Documentation
        run: nix build .#buildDocs

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: result

      - name: Deploy to Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
